### ISSUE TITLE
3rd Macro Type flag

### ISSUE THREAD

**Issue by moon6969** [mayanez/dumang-keyboard-ctrl#12]
Just for future reference...
```
class MacroType:
    KEYDOWN = 0x01
    KEYUP = 0x02
```
I noticed a 3rd Macro type flag = 0x04. It appears to be used to split the macro parts into 2 sections - first executed on the physical DuMang key down, and the 2nd on key up.
The DuMang software Macro record function uses it for "Dual Sections Mode" and "Key Combination Mode".
0x05 & 0x07 are used for the macro loop modes.

**Comment by mayanez** [comment]
Thanks for the info! I'll need to look into this more closely since I haven't had a need for more advanced macro configurations. If you end up finding out any additional information please keep me posted. Also, feel free to submit a PR and I'll gladly review it and merge it in :smiley:

**Comment by mayanez** [comment]
I finally got around to needing this macro feature myself so I implemented support for it. It is now named `WAIT_KEYUP`.
