### ISSUE TITLE
This project is generally useable/maintained/healthy/not-lacking-key-features? (cuz I got this vague intuitive sense people talk about the dumang surprisingly little, but maybe that's just cuz "Beyond Q"'s non-Chinese/English marketing is lacking?)

### ISSUE THREAD

**Issue by dwawlyn** [mayanez/dumang-keyboard-ctrl#13]
Hi, I'm interested in getting a dumang,
but I got this vague intuitive sense there might be something wrong with it, such that I'm not sure if it's practically useable?

But I think this intuition might just be coming from the fact that I've seen surprisingly few people talk about the dumang,
and I guess *that* might just be because "Beyond Q"'s non-Chinese/English marketing is lacking for some other reason?
(ie, some reason *other than* "there's something wrong with it, so they don't bother.")

[
btw,
I think you meant the link on your readme to go to `www.beyondq.com`?
cuz it actually goes to `https://github.com/mayanez/dumang-keyboard-ctrl/blob/master/www.beyondq.com`
]

---
So yeah, this project actually *is* generally useable/maintained/healthy?
Like, it's not lacking key features that us nerds obsessed with ergonomic keyboard layouts generally need?
Like, support for wacky modifier-layer stuff, chording, whatever?

A few more concrete examples from my current keyboard:

- I hit right and left shift together to toggle capslock

- I have a key that gets a "punctuation layer", and a key that gets a "function-key layer", and if I hit them together, I get a "digit-layer"

- I have some keys that do stuff like, a single key gets "function-key layer + ctrl" together at once, or "ctrl + alt" together, etc

**Comment by mayanez** [comment]
I don't reprogram my keyboard all the time, but the project is used/maintained. I rely on the sync layer to allow for all the fancy features you mention across the two keyboard halves.  

With regards to BeyondQ, my understanding is they are still in operation, but their market outside of China is quite limited. It's a shame since I think it is quite excellent hardware that should be made more accessible for others to enjoy. 

I'm not sure how regularly others use this project, but some have certainly contributed to it. If you do encounter any particular issue feel free to open a PR or an issue.

> [
btw,
I think you meant the link on your readme to go to www.beyondq.com?
cuz it actually goes to https://github.com/mayanez/dumang-keyboard-ctrl/blob/master/www.beyondq.com
]

Good catch. I'll make sure to update that.

**Comment by dwawlyn** [comment]
Cool!

> With regards to BeyondQ, my understanding is they are still in operation, but their market outside of China is quite limited.
> It's a shame since I think it is quite excellent hardware that should be made more accessible for others to enjoy.

I totally agree, it looks *SO* cool, and I feel like it should be *SUPER* popular worldwide!
[
*never* have to deal with stupid stuff like this again!:
![how thumbs work](https://preview.redd.it/g9ilknboyjp11.jpg?width=720&auto=webp&s=2336b435ea1aaf4cf78e60610d46abea130dfabf)

or like, this xD :
![how did this even *happen*? I usually never say this, but... were they *literally* on drugs?](https://i.imgur.com/dE3F5TB.jpeg)
]

But the very fact that it looks *SO* cool, and yet... I pretty much never heard anything about it...
made me suspicious that there was something somehow *wrong* with it, rendering it somehow unuseable for practical purposes.

Anyway, it's probably gonna take me quite a while to get around to actually starting on the project of getting my own one, but...

- can you tell me if there's any active community at all for this apparently hyper-specific little niche of ours here?

and

- do you know if it's possible to somehow adapt it to use choc V1 switches instead of MX?

**Comment by mayanez** [comment]
> can you tell me if there's any active community at all for this apparently hyper-specific little niche of ours here?

No idea how large the community is tbh. 

> do you know if it's possible to somehow adapt it to use choc V1 switches instead of MX?

I'm not sure. From my research, the pinout is not the same so without some heavy modification it's probably not possible.
