### ISSUE TITLE
dumang-config error with any command

### ISSUE THREAD

**Issue by ghost** [mayanez/dumang-keyboard-ctrl#3]
![image](https://user-images.githubusercontent.com/10449980/92258317-ed4ed500-eed6-11ea-878d-53de4fb718cf.png)

Any command gives the same error. 

Maybe related:
When installing dependencies, I noticed that there is no libudev on Ubuntu 20.04 so I installed libudev1 and libudev-dev instead hoping that would work.

All other dependencies, including python ones are installed.

**Comment by mayanez** [comment]
I've updated the `setup.py` and also added a script for `apt-get` for Debian (https://github.com/mayanez/dumang-keyboard-ctrl/blob/master/install/debian/install.sh), but I suspect it should be equivalent to Ubuntu. Give it a shot and let me know.

**Comment by ghost** [comment]
Just running the command you linked didn't change anything, I already had all of that installed before installing the dumand-keyboard-ctrl. Do you have any other ideas or is there any info I can provide to help you diagnose the issue?

**Comment by mayanez** [comment]
It seems like you might not have the keyboard plugged in or that you haven't properly configured the `udev` rules. If you look closer at the error message you'll see a `OSError: open failed. Likely permissions error.` You'll need to copy the provided `udev/51-dumang.rules` into the appropriate location for your distro. Refer to the `install/archlinux/PKGBUILD` for the paths. I suspect the paths for Ubuntu should be the same.

Unrelated, but it seems like you are using v0.0.1, consider using the `master` branch as well as I haven't updated PyPI yet.

**Comment by ghost** [comment]
I have put the 51-dumang.rules into /etc/udev/rules.d/ before as that was what I found online to be one of the suggested locations for ubuntu - after moving it to /usr/lib/udev/rules.d/ it seems to work fine.

Many thanks for your time and efforts!
